#baseURL = "https://antonioagudo.com/"
baseURL = "https://festive-jackson-9ed7d0.netlify.com/"
languageCode = "de-de"
defaultContentLanguage = "de"
title = "Antonio Agudo"
#theme = "hugo-universal-theme"
theme = "personal-web"
style="blue"
canonifyurls = true
paginate = 3
copyright = "Copyright © 2019, Antonio Agudo. All rights reserved."
pygmentsCodeFences = true
pygmentsUseClasses = true

[params.intro]
  main = "Hi, ich bin Antonio"
  sub = "Ich bin freiberuflicher Softwareentwickler und Unternehmer"

[taxonomies]
  programming = "programming"
  general = "general"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.social]
	linkedin = "https://linkedin.com/in/antonioagudo"
	twitter = "https://twitter.com/keyboardsamurai"
	github = "https://github.com/keyboardsamurai"

[params.assets]
  favicon = ""
  customCSS = "css/custom.css"

[params.sidebar]
  backgroundImage = 'images/temple-sidebar.jpg' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "/images/antonio-profile.jpg" # - default "/images/edna-west.jpg"

[params.contact]
  email = ""
  text= "" # text of the contact link in the sidebar. If email params.contact.email is defined

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  title = "Blog section"
  url = "/post/"
  weight = -80

[[menu.main]]
  identifier = "portfolio"
  name = "Portfolio"
  title = "Portfolio section"
  url = "/portfolio/"
  weight = -90

[[menu.main]]
  identifier = "about"
  name = "Über mich"
  title = "Über mich"
  url = "/about/"
  weight = -110


[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
