baseURL = "https://festive-jackson-9ed7d0.netlify.com/"
languageCode = "de-de"
title = "Antonio Agudo - Softwareentwicklung"
theme = "kross-hugo-portfolio-template"
summaryLength = "10"
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsstyle = "monokai"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "/css/custom.css"


  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"

  [[params.plugins.js]]
  URL = "plugins/lazyYT/lazyYT.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/shuffle/shuffle.min.js"


# navigation
[menu]

  [[menu.main]]
  name = "Über"
  URL = "about"
  weight = 2

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 3

  [[menu.main]]
  name = "Portfolio"
  URL = "portfolio"
  weight = 4

  [[menu.main]]
  name = "Kontakt"
  URL = "contact"
  weight = 5


[params]
logo = "images/logo.png"
home = "Start"
# Meta data
description = "Antonio Agudo - Exptertise in Softwareentwicklung für Konzerne und Startups"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"

  # Preloader
  [params.preloader]
  enable = true

  [params.contact]
  enable = true
  formAction = "#" #contact form works with formspree.io

  [params.footer]
  email = ""
  phone = "+49 (0) 170 1885991"
  address = "Eigelstein 57-59, 50688 Köln"
